#!/usr/bin/env python3
"""
Security Vulnerability Scanner - Environment Setup Script

This script helps you set up the environment configuration for the pipeline.
Run this script to interactively create your .env file.
"""

import os
import shutil
from pathlib import Path


def create_env_file():
    """Interactive setup to create .env file from template."""
    
    print("🚀 Security Vulnerability Scanner - Environment Setup")
    print("=" * 50)
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    # Copy sample file as starting point
    sample_file = Path(".env.sample")
    if sample_file.exists():
        shutil.copy(sample_file, env_file)
        print("✅ Created .env file from template")
    else:
        print("❌ .env.sample file not found!")
        return
    
    print("\n📝 Please provide the following information:")
    print("   (Press Enter to keep default values)")
    
    # Collect configuration
    config = {}
    
    print("\n🏢 GitHub Configuration:")
    config['GITHUB_ENTERPRISE_URL'] = input("GitHub Enterprise URL (default: https://api.github.com): ").strip() or "https://api.github.com"
    config['GITHUB_TOKEN'] = input("GitHub Personal Access Token (required): ").strip()
    config['GITHUB_ORG'] = input("GitHub Organization name (required): ").strip()
    
    # Validate required fields
    if not config['GITHUB_TOKEN']:
        print("❌ GitHub token is required!")
        return
    
    if not config['GITHUB_ORG']:
        print("❌ GitHub organization is required!")
        return
    
    # Optional configurations
    print("\n⚙️  Optional Configuration (press Enter to skip):")
    max_repos = input("Max repositories to scan (leave empty for all): ").strip()
    if max_repos and max_repos.isdigit():
        config['MAX_REPOSITORIES'] = max_repos
    
    output_dir = input("Output directory (default: ./reports): ").strip()
    if output_dir:
        config['OUTPUT_DIR'] = output_dir
    
    # Write configuration to .env file
    try:
        with open(env_file, 'w') as f:
            f.write("# Security Vulnerability Scanner - Environment Configuration\n")
            f.write("# Generated by setup script\n\n")
            
            f.write("# GitHub Enterprise Configuration\n")
            f.write(f"GITHUB_ENTERPRISE_URL={config['GITHUB_ENTERPRISE_URL']}\n")
            f.write(f"GITHUB_TOKEN={config['GITHUB_TOKEN']}\n")
            f.write(f"GITHUB_ORG={config['GITHUB_ORG']}\n\n")
            
            if 'MAX_REPOSITORIES' in config:
                f.write("# Scanning Limits\n")
                f.write(f"MAX_REPOSITORIES={config['MAX_REPOSITORIES']}\n\n")
            
            if 'OUTPUT_DIR' in config:
                f.write("# Output Configuration\n")
                f.write(f"OUTPUT_DIR={config['OUTPUT_DIR']}\n\n")
        
        print("\n✅ Environment file created successfully!")
        print(f"📁 Configuration saved to: {env_file.absolute()}")
        
        # Security reminder
        print("\n🔒 Security Reminder:")
        print("   • Never commit your .env file to version control")
        print("   • Keep your GitHub token secure")
        print("   • Regenerate tokens periodically")
        
        # Next steps
        print("\n🚀 Next Steps:")
        print("   • The pipeline will auto-create virtual environment and install dependencies")
        print("   • Simply run: python security_pipeline.py")
        print("   • Check the reports/ directory for output")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")


def check_requirements():
    """Check if required packages are installed."""
    
    print("\n🔍 Checking requirements...")
    
    required_packages = [
        'requests', 'pandas', 'PyGithub', 'openpyxl', 'python-dotenv'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_').replace('PyGithub', 'github'))
            print(f"   ✅ {package}")
        except ImportError:
            print(f"   ❌ {package}")
            missing_packages.append(package)
    
    if missing_packages:
        print(f"\n📦 Missing packages: {', '.join(missing_packages)}")
        print("   Run: pip install -r requirements.txt")
        return False
    else:
        print("\n✅ All required packages are installed!")
        return True


def main():
    """Main setup function."""
    
    print("🔧 Security Vulnerability Scanner Setup")
    print("=" * 40)
    
    # Check if we're in the right directory
    if not Path("security_pipeline.py").exists():
        print("❌ Please run this script from the project root directory")
        print("   (where security_pipeline.py is located)")
        return
    
    # Check requirements
    if not check_requirements():
        response = input("\nContinue with environment setup anyway? (y/N): ").strip().lower()
        if response != 'y':
            return
    
    # Create environment file
    create_env_file()


if __name__ == "__main__":
    main()